1.MSSV: 20520435

2.Họ tên: Nguyễn Duy Đạt

3.Bài tập: 1

4.Ngày thực hiện: 23/09/2022

# Bước 1: Cài đặt thư viện geopandas

In [ ]:
%cd "/content/drive/MyDrive/CS116 "

/content/drive/MyDrive/CS116

In [ ]:
!pip install geopandas

# Bước 2: git clone https://github.com/CityScope/CSL_HCMC

In [ ]:
!git clone https://github.com/CityScope/CSL_HCMC.git

Cloning into 'CSL_HCMC'...
remote: Enumerating objects: 1957, done.
remote: Counting objects: 100% (46/46), done.
remote: Compressing objects: 100% (45/45), done.
remote: Total 1957 (delta 7), reused 1 (delta 1), pack-reused 1911
Receiving objects: 100% (1957/1957), 169.10 MiB | 11.88 MiB/s, done.
Resolving deltas: 100% (1056/1056), done.
Checking out files: 100% (542/542), done.

# Bước 3: dùng geopandas để đọc shapefile trong /Data/GIS/Population/population_HCMC/population_shapefile/Population_Ward_Level.shp

In [ ]:
%cd "/content/drive/MyDrive/CS116 /CSL_HCMC/Data/GIS/Population/population_HCMC/population_shapefile"

/content/drive/MyDrive/CS116 /CSL_HCMC/Data/GIS/Population/population_HCMC/population_shapefile

In [ ]:
import geopandas
data = geopandas.read_file("Population_Ward_Level.shp")

In [ ]:
data

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry
0,Tan Dinh,District 1,26734,760,Ward,26571.0,23258.0,41942.70,36713.10,3679.098196,6.334981e+05,"POLYGON ((684350.511 1193546.266, 684363.810 1..."
1,Ben Nghe,District 1,26740,760,Ward,13580.0,10633.0,5480.09,4290.86,6978.149149,2.478041e+06,"POLYGON ((686564.657 1193462.473, 686588.924 1..."
2,Cau Ong Lanh,District 1,26752,760,Ward,12917.0,10737.0,56878.90,47279.50,2260.705105,2.270938e+05,"POLYGON ((685922.373 1190479.807, 685914.160 1..."
3,Nguyen Thai Binh,District 1,26746,760,Ward,13197.0,9716.0,26798.80,19730.00,3320.174618,4.924426e+05,"POLYGON ((685966.333 1190513.667, 685944.353 1..."
4,Co Giang,District 1,26755,760,Ward,18967.0,11517.0,53327.60,32381.20,2525.453814,3.556650e+05,"POLYGON ((685514.573 1190211.431, 685547.521 1..."
...,...,...,...,...,...,...,...,...,...,...,...,...
317,Tan Hung Thuan,District 12,26787,761,Ward,28892.0,33467.0,16053.40,18595.50,6271.308704,1.799659e+06,"POLYGON ((677816.513 1197206.772, 677796.932 1..."
318,Ward 17,Go Vap,26875,764,Ward,44226.0,54728.0,38061.20,47099.30,6385.950275,1.161947e+06,"POLYGON ((683516.949 1200006.226, 683509.721 1..."
319,Ward 8,Go Vap,26898,764,Ward,26545.0,32778.0,22751.50,28093.70,5409.821020,1.166701e+06,"POLYGON ((680928.492 1199066.285, 680984.889 1..."
320,Ward 9,Go Vap,26897,764,Ward,26785.0,34596.0,31843.10,41129.20,3950.799798,8.411288e+05,"POLYGON ((681120.443 1199640.183, 681120.846 1..."
321,Ward 12,Go Vap,26881,764,Ward,50356.0,60502.0,35096.20,42167.60,4848.143508,1.434747e+06,"POLYGON ((679970.916 1198480.707, 679932.874 1..."

# Bước 4: hãy thực hiện các tác vụ truy vấn sau

- Phường nào có diện tích lớn nhất
- Phường nào có dân số 2019 (Pop_2019) cao nhất
- Phường nào có diện tích nhỏ nhất
- Phường nào có dân số thấp nhất (2019)
- Phường nào có tốc độ tăng trưởng dân số nhanh nhất (dựa trên Pop_2009 và Pop_2019)
- Phường nào có tốc độ tăng trưởng dân số thấp nhất
- Phường nào có biến động dân số nhanh nhất
- Phường nào có biến động dân số chậm nhất
- Phường nào có mật độ dân số cao nhất (2019)
- Phường nào có mật độ dân số thấp nhất (2019)

In [ ]:
# 1. Phường nào có diện tích lớn nhất
data_com_name = data[data.Shape_Area == max(data.Shape_Area)]
data_com_name

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry
204,Ly Nhon,Can Gio,27682,787,Commune,5696.0,5266.0,35.3378,32.6701,68958.528608,1.611939e+08,"POLYGON ((703990.602 1160907.838, 704139.338 1..."

Phường Lý Nhơn ở Cần Giờ có diện tích lớn nhất

In [ ]:
# 2. Phường nào có dân số 2019 (Pop_2019) cao nhất
data_pop_2019 = data[data.Pop_2019 == max(data.Pop_2019)]
data_pop_2019

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry
168,Vinh Loc A,Binh Chanh,27601,785,Commune,49946.0,124709.0,2530.93,6319.41,19808.888559,1.973287e+07,"POLYGON ((669872.381 1199077.678, 669922.073 1..."

Phường Vĩnh Lộc A ở Bình Chánh có dân số 2019 (Pop_2019) cao nhất

In [ ]:
# 3. Phường nào có diện tích nhỏ nhất
data_com_name = data[data.Shape_Area == min(data.Shape_Area)]
data_com_name

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry
71,Ward 3,District 10,27205,771,Ward,7759.0,7245.0,76334.1,71277.3,1556.320657,101642.928821,"POLYGON ((682485.431 1189922.970, 682510.266 1..."

Phường 3 ở Quận 10 có diện tích nhỏ nhất

In [ ]:
# 4. Phường nào có dân số thấp nhất (2019)
data_pop_2019 = data[data.Pop_2019 == min(data.Pop_2019)]
data_pop_2019

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry
218,An Khanh,District 2,27106,769,Ward,15659.0,223.0,8830.98,125.762,6715.625464,1.773186e+06,"POLYGON ((688894.225 1192163.773, 688895.628 1..."

Phường An Khánh ở Quận 2 có dân số 2019 (Pop_2019) nhỏ nhất

In [ ]:
# 5. Phường nào có tốc độ tăng trưởng dân số nhanh nhất (dựa trên Pop_2009 và Pop_2019)
data['Speed_of_Growth'] = (data['Pop_2019'] -data['Pop_2009']) / data['Pop_2009']

In [ ]:
data_speed_max = data[data.Speed_of_Growth == max(data.Speed_of_Growth)]
data_speed_max

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry,Speed_of_Growth
211,Phu Huu,District 9,26866,763,Ward,7265.0,22216.0,614.811,1880.06,18842.507391,1.181706e+07,"POLYGON ((694734.189 1193824.448, 694735.625 1...",2.057949

Phường Phú Hữu ở Quận 9 có tốc độ tăng trưởng dân số nhanh nhất (dựa trên Pop_2009 và Pop_2019)

In [ ]:
# 6. Phường nào có tốc độ tăng trưởng dân số thấp nhất (dựa trên Pop_2009 và Pop_2019)
data_speed_min = data[data.Speed_of_Growth == min(data.Speed_of_Growth)]
data_speed_min

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry,Speed_of_Growth
218,An Khanh,District 2,27106,769,Ward,15659.0,223.0,8830.98,125.762,6715.625464,1.773186e+06,"POLYGON ((688894.225 1192163.773, 688895.628 1...",-0.985759

Phường An Khánh ở Quận 2 có tốc độ tăng trưởng dân số thấp nhất (dựa trên Pop_2009 và Pop_2019)

In [ ]:
# 7. Phường nào có biến động dân số nhanh nhất
data['volatility'] = data['Pop_2019'] -data['Pop_2009']

In [ ]:
data_volatility_max = data[data.volatility == max(data.volatility)]
data_volatility_max

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry,Speed_of_Growth,volatility
168,Vinh Loc A,Binh Chanh,27601,785,Commune,49946.0,124709.0,2530.93,6319.41,19808.888559,1.973287e+07,"POLYGON ((669872.381 1199077.678, 669922.073 1...",1.496877,74763.0

Phường Vĩnh Lộc A ở Bình Chánh có biến động dân số nhanh nhất

In [ ]:
# 8. Phường nào có biến động dân số chậm nhất
data_volatility_min = data[data.volatility == min(data.volatility)]
data_volatility_min

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry,Speed_of_Growth,volatility
218,An Khanh,District 2,27106,769,Ward,15659.0,223.0,8830.98,125.762,6715.625464,1.773186e+06,"POLYGON ((688894.225 1192163.773, 688895.628 1...",-0.985759,-15436.0

Phường An Khánh ở Quận 2 có biến động dân số chậm nhất

In [ ]:
# 9. Phường nào có mật độ dân số cao nhất (2019)
data['population_density'] = data['Pop_2019'] / data['Shape_Area']

In [ ]:
data_population_density_max = data[data.population_density == max(data.population_density)]
data_population_density_max

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry,Speed_of_Growth,volatility,population_density
16,Ward 8,District 4,27268,773,Ward,16221.0,15321.0,101839.0,96188.7,2623.543439,159274.140239,"POLYGON ((686132.663 1190298.153, 686136.360 1...",-0.055484,-900.0,0.096193

Phường 8 quận 4 có mật độ dân số cao nhất (2019)

In [ ]:
# 10. Phường nào có mật độ dân số thấp nhất (2019)
data_population_density_min = data[data.population_density == min(data.population_density)]
data_population_density_min

,Com_Name,Dist_Name,Com_ID,Dist_ID,Level,Pop_2009,Pop_2019,Den_2009,Den_2019,Shape_Leng,Shape_Area,geometry,Speed_of_Growth,volatility,population_density
204,Ly Nhon,Can Gio,27682,787,Commune,5696.0,5266.0,35.3378,32.6701,68958.528608,1.611939e+08,"POLYGON ((703990.602 1160907.838, 704139.338 1...",-0.075492,-430.0,0.000033

Phường Lý Nhơn huyện Cần Giờ có mật độ dân số thấp nhất (2019)